gitGraph LR:
    commit id: "c1" type: HIGHLIGHT tag: "v1.0"
    commit
    branch feature
    checkout feature
    commit id: "c2"
    checkout main
    commit
    merge feature id: "m1" tag: "merge-tag"
